default: true
MD013: false # Line length - often hard to maintain in docs
MD033: false # Inline HTML - sometimes needed for specific formatting
MD041: false # First line in file should be a top level heading - not always true for frontmatter files
